["AppData/Roaming/navi/cheats/docker.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/container/docker.cheat"
["AppData/Roaming/navi/cheats/kubernetes.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/container/kubernetes.cheat"
["AppData/Roaming/navi/cheats/git.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/code/git.cheat"
