[".local/share/navi/cheats/brew.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/pkg_mgr/apt.cheat"
[".local/share/navi/cheats/apt.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/pkg_mgr/brew.cheat"
[".local/share/navi/cheats/javascript.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/pkg_mgr/javascript.cheat"
[".local/share/navi/cheats/curl.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/network/curl.cheat"
[".local/share/navi/cheats/network.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/network/network.cheat"
[".local/share/navi/cheats/docker.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/container/docker.cheat"
[".local/share/navi/cheats/kubernetes.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/container/kubernetes.cheat"
[".local/share/navi/cheats/git.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/code/git.cheat"

[".local/bin/ssh-ident"]
    type = "file"
    url = "https://raw.githubusercontent.com/ccontavalli/ssh-ident/66a00104057411d85592411455261284d08bb065/ssh-ident"
    executable = true

[".config/zsh/ohmyzsh-git-plugin.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/5d3e86e2a48adf7a308773f8f1b725d187c7c5ef/plugins/git/git.plugin.zsh"
